before_commands:
    - 'composer install --prefer-source --no-interaction --dev'
filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'src/Elepunk/Orchestrate/stubs/*'
        - 'vendor/*'
        - 'tests/*'
tools:
    php_analyzer: true
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_code_coverage:
        config_path: phpunit.xml
    php_cpd:
        excluded_dirs:
            - vendor
            - tests
    php_loc:
        excluded_dirs:
            - vendor
            - tests
            - src/Elepunk/Orchestrate/stubs
    php_pdepend:
        excluded_dirs:
            - vendor
            - tests
            - src/Elepunk/Orchestrate/stubs/